version: 2 
sources:
   - name: raw
     database: <project_id>
     schema: gz_raw_data
     loader: bigquery
     freshness:
       warn_after: {count: 12, period: hour}
     tables:
       - name: sales
         identifier: raw_gz_sales
         description: sales of Greenweez / we have on row per product_id found in each orders_id
         loaded_at_field: date_date
         columns:
           - name: date_date
             description: date of purchase