version: 2 

sources:
  - name: gz_raw_data
    tables:
      - name: ship
        identifier: raw_gz_ship
      - name: sales
        identifier: raw_gz_sales
      - name: product
        identifier: raw_gz_product
      